version: "3"
services:
  app:
    build: .
    command: make test
    environment:
      - SHELL=/bin/sh
    volumes:
      - ./maybe/:/go/src/app/maybe/
      - ./test/:/go/src/app/test/
      - ./Makefile:/go/src/app/Makefile

